cache:
  key: ${CI_BUILD_REF_NAME}

stages:
  - build
  - run
  - deploy

compile:
  stage: build
  image: eclipse-temurin:11.0.26_4-jdk-alpine-3.21
  script:
    - javac -d out/production/crypto2/ src/Main.java
  artifacts:
    paths:
      - out/production/crypto2/

export:
  stage: run
  image: eclipse-temurin:11.0.26_4-jre-alpine-3.21
  tags: [ saas-linux-medium-amd64 ]
  script:
    - cd out/production/crypto2/
    - java "-Dfile.encoding=UTF-8" "-Dconsole.encoding=UTF-8" Main
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

pages:
  stage: deploy
  image: alpine:latest
  script:
    - ""
  artifacts:
    paths:
      - public
  only:
    - main